export interface EventItem { slug: string; title: string; image: string;  date: string; time: string; location: string; }
export const events : EventItem[] = [
    {
        slug: "react-conf-2026",
        image: "/images/event1.webp",
        title: "React Conf 2026",
        location: "San Francisco, CA",
        date: "March 15, 2026",
        time: "9:00 AM - 6:00 PM",
    },
    {
        slug: "nextjs-summit",
        image: "/images/event2.webp",
        title: "Next.js Summit",
        location: "Austin, TX",
        date: "April 22, 2026",
        time: "10:00 AM - 5:00 PM",
    },
    {
        slug: "javascript-world",
        image: "/images/event3.webp",
        title: "JavaScript World Conference",
        location: "New York, NY",
        date: "May 8, 2026",
        time: "8:30 AM - 7:00 PM",
    },
    {
        slug: "ai-hackathon-2026",
        image: "/images/event4.webp",
        title: "AI Innovation Hackathon",
        location: "Seattle, WA",
        date: "June 14-16, 2026",
        time: "48 Hours",
    },
    {
        slug: "web3-developer-meetup",
        image: "/images/event5.webp",
        title: "Web3 Developer Meetup",
        location: "Miami, FL",
        date: "July 20, 2026",
        time: "6:00 PM - 9:00 PM",
    },
    {
        slug: "fullstack-conference",
        image: "/images/event6.webp",
        title: "Full Stack Conference",
        location: "Denver, CO",
        date: "August 12, 2026",
        time: "9:00 AM - 6:00 PM",
    },
    {
        slug: "devops-unleashed",
        image: "/images/event7.webp",
        title: "DevOps Unleashed",
        location: "Chicago, IL",
        date: "September 5, 2026",
        time: "8:00 AM - 5:30 PM",
    },

    {
        slug: "cybersecurity-conference",
        image: "/images/event8.webp",
        title: "Cybersecurity Conference",
        location: "Boston, MA",
        date: "November 2, 2026",
        time: "8:00 AM - 7:00 PM",
    },
    {
        slug: "data-science-hackathon",
        image: "/images/event9.webp",
        title: "Data Science Hackathon",
        location: "San Diego, CA",
        date: "December 7-9, 2026",
        time: "72 Hours",
    },
    {
        slug: "cloud-native-meetup",
        image: "/images/event10.webp",
        title: "Cloud Native Meetup",
        location: "Portland, OR",
        date: "January 15, 2025",
        time: "6:30 PM - 9:00 PM",
    },

];